---
title: Perfil.med.br
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  medicos:
    title: medicos
    output: true
